"""Build the two WordPress page templates (sales page + watch library) as single, self-contained PHP files.

Each template prints its own complete HTML document: no get_header()/get_footer(), so the theme's header,
footer and stylesheets never load and can't restyle the page. CSS, fonts, images and scripts are inlined;
only the videos live outside the file (wp-content/uploads/eig-ondemand/videos/ by default).

  python3 tools/make-wp-templates.py      ->  site/wordpress/templates/eig-day2-on-demand.php
                                              site/wordpress/templates/eig-day2-on-demand-watch.php
"""
import re, base64, pathlib, mimetypes, json

ROOT = pathlib.Path(__file__).resolve().parent.parent / 'site'
OUT = ROOT / 'wordpress' / 'templates'
mimetypes.add_type('image/webp', '.webp'); mimetypes.add_type('font/woff2', '.woff2')

def data(p):
    p = (ROOT / p).resolve(); m = mimetypes.guess_type(str(p))[0] or 'application/octet-stream'
    return f'data:{m};base64,' + base64.b64encode(p.read_bytes()).decode()

def safe_js(txt):
    # an inline script ends at the first "</script", even inside a comment or string
    return txt.replace('</script', '<\\/script')

def css_inline(rel):
    txt = (ROOT / rel).read_text()
    return re.sub(r"url\('\.\./([^']+)'\)", lambda u: f"url('{data(u.group(1))}')", txt)

SETTINGS_COMMON = """
// ---- Settings ------------------------------------------------------------------------------------
// Page addresses are found automatically from whichever pages use these two templates.
$eigod_settings = array(
  'salesUrl'  => eigod_page_url('eig-day2-on-demand.php', '/day-2-on-demand/'),
  'watchUrl'  => eigod_page_url('eig-day2-on-demand-watch.php', '/day-2-on-demand/watch/'),
  // Where the encoded talks are uploaded: <videoBase>/09/master.m3u8, <videoBase>/10/master.m3u8, ...
  'videoBase' => content_url('/uploads/eig-ondemand/videos/'),
  // false = test mode, everything is open. true = the watch page needs a verified purchase
  // (see wordpress/README.md, "Turn on gating"). Set the same value in both templates.
  'gated'     => false,%(extra)s
);
// true = also run wp_head()/wp_footer(), so plugins such as analytics, pixels or SEO can add their tags.
// This also loads your theme's stylesheet; the page is built to withstand that, but off is cleanest.
$eigod_wp_hooks = false;
// --------------------------------------------------------------------------------------------------
"""
EXTRA_SALES = """
  // Pricing shown on the page. Stripe charges whatever the Payment Link itself is set to.
  'price'             => 149,
  'currency'          => 'USD',
  'accessTerm'        => '12 months',
  'stripePaymentLink' => 'https://buy.stripe.com/test_XXXXXXXXXXXX',
  // Social sharing image (upload it, or point this at any image in your Media Library).
  'ogImage'           => content_url('/uploads/eig-ondemand/og-image.jpg'),"""

HEADER = """<?php
/*
 * Template Name: %(name)s
 * Description: %(desc)s
 *
 * STANDALONE PAGE TEMPLATE. It prints its own complete page, so your theme's header, footer and
 * stylesheet are not used and can't interfere. Everything it needs is inside this file except the videos.
 *
 * Install:
 *   1. Upload this file into your active theme's folder, wp-content/themes/<your-theme>/ (use a child
 *      theme if your theme gets updates, or the file is lost on update).
 *   2. Pages > Add New: set the title, choose Template "%(name)s", Publish. Leave the content empty.
 *   3. %(step3)s
 * Generated by tools/make-wp-templates.py; edit the settings below, rebuild for anything else.
 */
if (!defined('ABSPATH')) exit;

if (!function_exists('eigod_page_url')) {
  // URL of the first published page using the given template file, else a fallback path.
  function eigod_page_url($template, $fallback) {
    $p = get_pages(array('meta_key' => '_wp_page_template', 'meta_value' => $template, 'number' => 1));
    return $p ? get_permalink($p[0]) : home_url($fallback);
  }
}
%(settings)s
?><!doctype html>
<html <?php language_attributes(); ?>>
<head>
"""

def build(page, out, name, desc, step3, extra):
    html = (ROOT / page).read_text()
    head, body = html.split('</head>', 1)
    head = head.split('<head>', 1)[1]
    body = body.split('<body>', 1)[1].split('</body>', 1)[0]

    # ---- head: keep meta + title, inline styles, drop preloads and file links
    metas = [l for l in head.strip().splitlines() if re.match(r'\s*<(meta|title)', l) and 'og:image' not in l]
    styles = [f'<style>{css_inline(m)}</style>' for m in re.findall(r'<link rel="stylesheet" href="(css/[^"]+)">', head)]
    styles += re.findall(r'<style>.*?</style>', head, re.S)
    icon = f'<link rel="icon" href="{data("assets/img/eig-mark.png")}">'
    og = "<?php if (!empty($eigod_settings['ogImage'])) : ?><meta property=\"og:image\" content=\"<?php echo esc_url($eigod_settings['ogImage']); ?>\"><?php endif; ?>" if 'og:title' in head else ''

    # ---- body: inline images, collect scripts
    scripts = re.findall(r'<script src="([^"]+)"></script>', body)
    body = re.sub(r'<script src="[^"]+"></script>\n?', '', body)
    body = re.sub(r'\s(srcset|sizes)="[^"]*"', '', body)
    body = re.sub(r'src="(assets/[^"]+)"', lambda m: f'src="{data(m.group(1))}"', body)
    body = re.sub(r'href="(assets/[^"]+)"', lambda m: f'href="{data(m.group(1))}"', body)

    inline = {p.stem: data(p.relative_to(ROOT)) for p in sorted((ROOT / 'assets/speakers').glob('*.webp'))}
    if page == 'watch.html':
        inline.update(__glass=data('assets/img/glass-1200.webp'), __mark=data('assets/img/eig-mark.webp'))
    js = ''.join(f'<script>{safe_js((ROOT / s).read_text())}</script>\n' for s in scripts)
    hls = ''
    if any('player.js' in s for s in scripts):
        # hls.js only runs in browsers without native HLS; embedded unparsed so Safari/iOS skip the cost
        hls = '<script type="text/plain" id="eigod-hls-src">' + safe_js((ROOT / 'js/vendor/hls.light.min.js').read_text()) + '</script>\n'

    php = HEADER % dict(name=name, desc=desc, step3=step3, settings=SETTINGS_COMMON % dict(extra=extra))
    php += '\n'.join(metas) + '\n' + og + '\n' + icon + '\n'
    php += "<?php if ($eigod_wp_hooks) wp_head(); ?>\n"
    php += '\n'.join(styles) + '\n'
    php += "<script>window.EIGOD_OVERRIDES = <?php echo wp_json_encode($eigod_settings); ?>;</script>\n"
    php += '</head>\n<body class="eigod-page">\n'
    php += body.strip() + '\n'
    php += '<script>window.EIGOD_INLINE=' + json.dumps(inline) + ';</script>\n' + hls + js
    php += "<?php if ($eigod_wp_hooks) wp_footer(); ?>\n</body>\n</html>\n"
    assert '<?xml' not in php
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / out).write_text(php)
    print(out, round(len(php) / 1e6, 2), 'MB')

build('index.html', 'eig-day2-on-demand.php', 'EIG Day 2 On-Demand Sales',
      'EIG Innovation Conference 2026: Day 2 on-demand sales page (standalone, no theme header/footer).',
      'Create the watch page the same way with the "EIG Day 2 On-Demand Watch" template.', EXTRA_SALES)
build('watch.html', 'eig-day2-on-demand-watch.php', 'EIG Day 2 On-Demand Watch',
      'EIG Innovation Conference 2026: Day 2 on-demand watch library (standalone, no theme header/footer).',
      'Make it a child of the sales page so its address is /day-2-on-demand/watch/ (any address works).', '')
